### ISSUE TITLE
An internal error occurred during: "Launching crsx3". GC overhead limit exceeded

### ISSUE THREAD

**Issue by mariaschett** [crsx/crsxeclipse#4]
![screen-eclipse](https://cloud.githubusercontent.com/assets/12652013/10511048/f6c04914-7336-11e5-8465-49dab8d55a54.png)
When I try to run a crsx program*, a build process starts up (see also 
screen shot), and does not stop until there is an error box after some time with:

An internal error occurred during: "Launching crsx3".
GC overhead limit exceeded

Some of my details:

Version: Mars.1 Release (4.5.1) (for Fedora, Mars 4.5 the plug-in didn't work, it just showed up as installed, but nowhere else)
Build id: 20150924-1200

$ java -version
openjdk version "1.8.0_60"
OpenJDK Runtime Environment (build 1.8.0_60-b27)
OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode)

*without the plug-in installed the program works as expected.

**Comment by jsebechlebsky** [comment]
Hi Maria, could you write me how have you tried to run the crsx example from Eclipse so I can try to recreate the issue?

**Comment by mariaschett** [comment]
Hi,

I just tried to reproduce myself and now the nature of the problem changed. 

Immediately after I open up Eclipse, "Updating projects 'crsx3' and 'crsx4', Building crsx3..." (see screenshot) starts and blocks everything.

To run crsx from Eclipse I usually use the run configuration with the arguments:

rules=/path/to/rules.crs
sink=net.sf.crsx.text.TextSink
term=Start[Term]
verbose=3
omit-properties
sortify

Is this what you expected or am I missing something?

Also, when I close Eclipse, I get the following error message and have to force quit: 
"The user operation is waiting for "Update .. jects 'crsx3' and 'crsx4'" to complete."

![screen-eclipse2](https://cloud.githubusercontent.com/assets/12652013/10575645/2c4bb45e-765e-11e5-86d6-4b5ffb8fa9a5.png)

**Comment by jsebechlebsky** [comment]
Hi Maria, I think it should be fixed in develop branch now. There was a bug in lexer causing it to freeze. Thank you for the bug report!

**Comment by mariaschett** [comment]
Thanks a lot for fixing it, it works now. I am really looking forward to using it.
