### ISSUE TITLE
Syntax Highlighting and /*comments*/

### ISSUE THREAD

**Issue by mariaschett** [crsx/crsxeclipse#5]
Hi,

there are some problems with the syntax highlighting and comments, I believe.

Two examples: 
- [crsx4/unification/mgu.crs](https://github.com/crsx/crsx4/blob/develop/src/unification/mgu.crs)
  Here, it starts only from line 204. After an inline comment, the syntax highlighting is off and many errors are shown.
- [crsx4/unification/state.crs](https://github.com/crsx/crsx4/blob/develop/src/unification/state.crs)
  Here, for some reason the syntax highlighting does not work from the beginning of the file.

Does this happen to you as well, or is it from my side? Do you want more examples?

Best, Maria

**Comment by jsebechlebsky** [comment]
Thanks for a report, that's certainly a bug! I think I don't need more examples of this particular problem, but if you would experience any other problems (not related to the comments), I will appreciate it.

**Comment by lionelvillard** [comment]
On the same topic, there is a problem with : 
![screen shot 2015-10-30 at 8 33 43 am](https://cloud.githubusercontent.com/assets/6598801/10845756/13413084-7ee1-11e5-8665-f7f8a31b57c2.png)

**Comment by jsebechlebsky** [comment]
Thanks for a bug report, I think it should work now.

**Comment by lionelvillard** [comment]
Yes this is fixed, thanks! (at least for the  comments)

**Comment by mariaschett** [comment]
It works --- Thanks!
