### ISSUE TITLE
Enhancement: Support of  *.term

### ISSUE THREAD

**Issue by mariaschett** [crsx/crsxeclipse#7]
Would it be possible to also handle ".term" files, containing only a term /\* and // comments */, in the crsx editor? 

I really like to use them for testing, as e.g. in [Elem.term](https://github.com/crsx/crsx4/blob/develop/tests/std/list/Elem.term).

I already tried to use the crsx editor by associating it with .term, but then (after some time) Eclipse complains about: 

"Error updating dirty state editor
java.lang.IllegalStateException: No IResourceServiceProvider found in registry for uri platform:/path/to/Elem.term"

**Comment by jsebechlebsky** [comment]
Hi Maria, I'll look at that :)

**Comment by jsebechlebsky** [comment]
Hi Maria, I think it is sufficient just to open *.term file in CRSX editor -> I've added .term extension to extensions handled by the plugin, so Eclipse will open .term files in CRSX editor by default.

**Comment by mariaschett** [comment]
Cool, I started to try it. For the moment it works fine. Thanks a lot!
